import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { usePaginatePosts } from "../useRequest"
import Post from "../components/Post"

export default function Home() {

  const {
    posts, 
    error, 
    isLoadingMore,
    size,
    setSize,
    isReachingEnd,
  } = usePaginatePosts("/posts")

  if (error) return <h1>Something went wrong!</h1>
  if (!posts ) return <h1>Loading...</h1>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My Post with useSWRInfinite</h1>

        {posts.map(post => (
          <Post post={post} key={post.id} />
        ))}

        <button disabled={isLoadingMore || isReachingEnd }
          onClick={()=> setSize(size + 1)}
        >
          { isLoadingMore 
          ? "Loading..."
          : isReachingEnd
          ? "No more posts"
          : "Load more"
        }
        </button>
     </div>
  )
}

// export default function Home() {

//   const { posts, error } = useGetPosts("/posts")

//   if (error) return <h1>Something went wrong!</h1>
//   if (!posts ) return <h1>Loading...</h1>
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <h1>Posts</h1>
//       {posts.map(post => (
//         <Post post={post} key={post.id} />
//       ))}

//      </div>
//   )
// }
